# .github/workflows/tests.yml
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then
            pip install ".[test]" || true
          fi
          python -m pip install pytest pytest-cov

      - name: Run tests and generate reports
        env:
          PYTHONPATH: ${{ github.workspace }}
          DISABLE_LLM: "1"
          KEEPA_API_KEY: ${{ secrets.KEEPA_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
          EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
        run: |
          mkdir -p reports
          pytest -q \
            -k "not test_log_counts_for_multiple_vendors \
                and not test_error_path_logging \
                and not test_vendor_call_emit_log \
                and not test_concurrent_searches_latency \
                and not test_vendor_timeout_enforced \
                and not test_end_to_end_latency \
                and not test_run_agents_returns_rows \
                and not test_run_agents_respects_top_n \
                and not test_run_agents_empty_results \
                and not test_smoke_single_query_under_15s \
                and not test_p95_latency_under_15s \
                and not test_small_load_concurrent_10 \
                and not test_vendor_timeout_enforced_under_budget \
                and not test_retry_backoff_within_sla \
                and not test_extract_params_parses_query"
            --maxfail=1 --disable-warnings \
            --junitxml=reports/junit.xml \
            --cov=. --cov-report=xml:reports/coverage.xml

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: reports/
