# .github/workflows/tests.yml
name: Tests

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']   # 3.13 can break some libs; bump if you need

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have a dev/CI requirements file, prefer that:
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # If your package defines extras for tests:
          if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then
            pip install ".[test]" || true
          fi
          # Ensure pytest is present even if not pinned above:
          python -m pip install pytest pytest-cov

      - name: Run tests and generate reports
        env:
          # Add any API keys/secrets you need for tests here
          KEEPA_API_KEY: ${{ secrets.KEEPA_API_KEY }}
        run: |
          mkdir -p reports
          pytest -q \
            --maxfail=1 --disable-warnings \
            --junitxml=reports/junit.xml \
            --cov=. --cov-report=xml:reports/coverage.xml

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: reports/
